CREATE TABLE `User` (
  `id` VARCHAR(191) NOT NULL, `username` VARCHAR(191) NOT NULL, `passwordHash` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NULL, `phone` VARCHAR(191) NULL, `role` ENUM('USER','ADMIN','SUPER_ADMIN') NOT NULL DEFAULT 'USER',
  `status` ENUM('ACTIVE','SUSPENDED') NOT NULL DEFAULT 'ACTIVE', `mustChangePassword` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `User_username_key`(`username`), UNIQUE INDEX `User_email_key`(`email`), UNIQUE INDEX `User_phone_key`(`phone`), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `Card` (
  `id` VARCHAR(191) NOT NULL, `cardNumber` VARCHAR(191) NOT NULL, `slug` VARCHAR(191) NOT NULL,
  `type` ENUM('EXPRESS','CUSTOM','BUSINESS') NOT NULL, `status` ENUM('PENDING','ACTIVE','SUSPENDED','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `userId` VARCHAR(191) NOT NULL, `activatedAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `Card_cardNumber_key`(`cardNumber`), UNIQUE INDEX `Card_slug_key`(`slug`), INDEX `Card_userId_idx`(`userId`), PRIMARY KEY (`id`),
  CONSTRAINT `Card_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `Profile` (
  `id` VARCHAR(191) NOT NULL, `userId` VARCHAR(191) NOT NULL, `firstName` VARCHAR(191) NULL, `lastName` VARCHAR(191) NULL, `photo` VARCHAR(191) NULL,
  `jobTitle` VARCHAR(191) NULL, `company` VARCHAR(191) NULL, `bio` TEXT NULL, `phone` VARCHAR(191) NULL, `whatsapp` VARCHAR(191) NULL, `email` VARCHAR(191) NULL,
  `website` VARCHAR(191) NULL, `linkedin` VARCHAR(191) NULL, `facebook` VARCHAR(191) NULL, `instagram` VARCHAR(191) NULL, `tiktok` VARCHAR(191) NULL, `location` VARCHAR(191) NULL,
  `design` ENUM('SIGNATURE','STUDIO','AURA') NOT NULL DEFAULT 'SIGNATURE', `showServices` BOOLEAN NOT NULL DEFAULT true, `isPublished` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `Profile_userId_key`(`userId`), PRIMARY KEY (`id`),
  CONSTRAINT `Profile_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `Service` (`id` VARCHAR(191) NOT NULL, `profileId` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `description` TEXT NULL, `position` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (`id`), CONSTRAINT `Service_profileId_fkey` FOREIGN KEY (`profileId`) REFERENCES `Profile`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `Design` (`id` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `slug` VARCHAR(191) NOT NULL, `previewImage` VARCHAR(191) NULL, `isActive` BOOLEAN NOT NULL DEFAULT true, UNIQUE INDEX `Design_slug_key`(`slug`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CardView` (`id` VARCHAR(191) NOT NULL, `cardId` VARCHAR(191) NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `userAgent` TEXT NULL, `referrer` TEXT NULL, PRIMARY KEY (`id`), CONSTRAINT `CardView_cardId_fkey` FOREIGN KEY (`cardId`) REFERENCES `Card`(`id`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
