CREATE TABLE `GalleryItem` (
  `id` VARCHAR(191) NOT NULL,
  `profileId` VARCHAR(191) NOT NULL,
  `image` VARCHAR(191) NOT NULL,
  `caption` VARCHAR(191) NULL,
  `position` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  CONSTRAINT `GalleryItem_profileId_fkey` FOREIGN KEY (`profileId`) REFERENCES `Profile`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `Profile` MODIFY `design` ENUM('GOLD','SILVER','BLACK','SIGNATURE','STUDIO','AURA') NOT NULL DEFAULT 'SIGNATURE';
UPDATE `Profile` SET `design` = CASE `design` WHEN 'GOLD' THEN 'SIGNATURE' WHEN 'SILVER' THEN 'STUDIO' WHEN 'BLACK' THEN 'AURA' ELSE `design` END;
ALTER TABLE `Profile` MODIFY `design` ENUM('SIGNATURE','STUDIO','AURA') NOT NULL DEFAULT 'SIGNATURE';
