"use server";
import bcrypt from "bcryptjs";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import {mkdir,writeFile} from "node:fs/promises";import path from "node:path";import {randomUUID} from "node:crypto";
async function storeImage(file:File){if(!file.size)return null;if(file.size>5*1024*1024||!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("Format ou taille d’image invalide");const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";const name=`${randomUUID()}.${ext}`;const dir=path.join(process.cwd(),"public","uploads");await mkdir(dir,{recursive:true});await writeFile(path.join(dir,name),Buffer.from(await file.arrayBuffer()));return `/uploads/${name}`}
export async function updateProfile(formData:FormData){const user=await requireUser();const get=(name:string)=>{const v=String(formData.get(name)||"").trim();return v||null};const services=String(formData.get("services")||"").split("\n").map(name=>name.trim()).filter(Boolean);const photo=await storeImage(formData.get("photo") as File);const gallery=await Promise.all((formData.getAll("gallery") as File[]).slice(0,6).map(storeImage));await prisma.profile.update({where:{userId:user.id},data:{firstName:get("firstName"),lastName:get("lastName"),jobTitle:get("jobTitle"),company:get("company"),bio:get("bio"),phone:get("phone"),whatsapp:get("whatsapp"),email:get("email"),website:get("website"),linkedin:get("linkedin"),facebook:get("facebook"),xUrl:get("xUrl"),instagram:get("instagram"),tiktok:get("tiktok"),location:get("location"),isPublished:formData.get("publish")==="on",...(photo?{photo}:{}),services:{deleteMany:{},create:services.map((name,position)=>({name,position}))},...(gallery.filter(Boolean).length?{gallery:{create:gallery.filter(Boolean).map((image,position)=>({image:image!,position}))}}:{})}});revalidatePath("/dashboard");user.cards.forEach(c=>revalidatePath(`/p/${c.slug}`));redirect("/dashboard/profile?saved=1")}
export async function updateDesign(formData:FormData){const user=await requireUser();const design=String(formData.get("design"));if(!["SIGNATURE","STUDIO","AURA"].includes(design))return;await prisma.profile.update({where:{userId:user.id},data:{design:design as "SIGNATURE"|"STUDIO"|"AURA"}});revalidatePath("/dashboard");user.cards.forEach(c=>revalidatePath(`/p/${c.slug}`));}
export async function changePassword(formData:FormData){const user=await requireUser();const password=String(formData.get("password")||"");const confirm=String(formData.get("confirmPassword")||"");if(password.length<10)redirect("/dashboard/security?error=short");if(password!==confirm)redirect("/dashboard/security?error=match");await prisma.user.update({where:{id:user.id},data:{passwordHash:await bcrypt.hash(password,12),mustChangePassword:false}});redirect("/dashboard?welcome=1")}
export async function toggleCardActivation(){const user=await requireUser();const card=user.cards[0];if(!card)return;await prisma.card.update({where:{id:card.id},data:{status:card.status==="ACTIVE"?"SUSPENDED":"ACTIVE",activatedAt:card.status==="ACTIVE"?null:new Date()}});revalidatePath("/dashboard");revalidatePath(`/p/${card.slug}`)}
export async function removeGalleryItem(formData:FormData){const user=await requireUser();const id=String(formData.get("id")||"");const profile=await prisma.profile.findUnique({where:{userId:user.id},select:{id:true}});if(!profile)return;await prisma.galleryItem.deleteMany({where:{id,profileId:profile.id}});revalidatePath("/dashboard/profile");user.cards.forEach(c=>revalidatePath(`/p/${c.slug}`));}
